### ISSUE TITLE
gc: clean up tmpdirs with dirEngine

### ISSUE THREAD

**Issue by cyphar** [cyphar/umoci#17]
This is going to be a bit of a layer violation, so I'll have to think about it. But basically we need to have a way to remove all of the temporary directories that have been left behind inside an OCI image.

**Comment by wking** [comment]
My preferred approach to this is to follow Git and give content a grace period before cleanup.  If a temp file or temp dir or unreferenced blob has not been touched in 24 hours (or whatever), it's probably a safe bet that nobody cares about it anymore.  That means you don't reclaim space until 24 hours after the crash / abandoned push, but those events should be rare locally.

**Comment by cyphar** [comment]
Thanks for your insight. However, that's not relevant here because `umoci gc` is an explicit command operating on a local image we are currently building.

**Comment by wking** [comment]
So is [`git gc`][1], see `gc.pruneExpire`.

[1]: https://git-scm.com/docs/git-gc

**Comment by cyphar** [comment]
Not _really_ comparable IMO. An OCI image is not like a git repo (aside from both being Merkle DAGs), and `umoci` is not intended to be used like `git`.

**Comment by wking** [comment]
Merkle DAG seems like enough similarity for sharing similar CAS GC approaches to me.  But I'm sure there are other approaches that will work too ;).

**Comment by cyphar** [comment]
TODO: Use `syscall.Flock` so that we can make sure we don't delete directories we shouldn't.
