### ISSUE TITLE
umoci: implement direct digest referencing

### ISSUE THREAD

**Issue by cyphar** [cyphar/umoci#22]
Currently we have to go through `refs` exclusively, which means that you can't tag a blob that doesn't already have a tag. This is a bit of a pain (though with `umoci init` it won't be a blocking issue). 

However, a nice way of fixing this would be implementing an indexer for an OCI image (which does the same sort of indexing that `umoci gc` does but in addition storing the `MediaType` of the object referenced). Then we could always guarantee that we had blob references for _most_ blobs, and we could then go with a backup option of just using `MediaType` as gospel.

The only downside to this approach is that layer diff blobs will not be practically usable (since we can't tell between a distributable and non-distributable blob -- though I'm not sure if the spec even says that a particular layer diff blob is in a strict binary between the two types). But we can just check for a `gzip` header (or just check that it's **not** JSON) and move on with our lives, and then not allow operations that directly reference those blobs.

We could also add an explicit `--mediatype` option that allows for overwriting of the detected mediatype (probably dangerous). Then we can just not allow operations on any untyped blob.

**Comment by wking** [comment]
On Sun, Nov 06, 2016 at 09:27:37AM -0800, Aleksa Sarai wrote:
> Currently we have to go through `refs` exclusively, which means that
> you can't tag a blob that doesn't already have a tag.

Tagging shouldn't be a particularly complicated operation.  The
low-level approach is to use something like oci-refs directly.  The
high-level approach is to add a new-image-generating tool (oboci?)
that prompts the user for this sort of thing, pushes the new DAG, and
pushes a tag referencing the generated root.  I'm not sure how much
need there is for a mid-level approach, where you know a blob's digest
but not it's type.

If you do need that mid-level approach, it seems like you could fetch
the blob by its digest and use peek-inside typing even without a
global digest → type index.  If you restrict your repository to OCI
types, you can have pretty reliable peek-inside typing.  As you point
out, ‘distributable’ is going to be hard to autodetect, but folks are
less likely to be tagging layers anyway.

> … though I'm not sure if the spec even says that a particular layer
> diff blob is in a strict binary between the two types…

If it has any non-distributable content in it, the whole layer will be
non-distributable.  If you want to distribute that layer's
distributable content, you'd need to make a new layer containing only
the distributable parts.

**Comment by cyphar** [comment]
I'm just going to implement it with `--mediatype` (with my current `cas.Blob` detection as the default). I'm not sure what I'm going to do with `oboci`.
