### ISSUE TITLE
umoci: implement gc

### ISSUE THREAD

**Issue by cyphar** [cyphar/umoci#3]
Because of how `umoci repack` is implemented (we create a bunch of new blobs and leave the old ones) we need to include a garbage collector that can clean up the trash after we've regenerated everything. A standard mark-and-sweep garbage collector will do.

A nice way of doing this would be to use `reflect` and to parse every `Descriptor`, adding every referenced descriptor to "black" coloured objects (with the default being "white"). Then the "white" coloured objects are removed.

**Comment by wking** [comment]
How are you going to identify descriptors with reflect?  I recommend keeping a map from media types to child-desciptor-extracting functions, but if you need something more generic (and less reliable) you could use `interface{}` to hunt for objects with at least size/mediaType/digest.

**Comment by cyphar** [comment]
[This](https://golang.org/pkg/reflect/#TypeOf).

**Comment by wking** [comment]
But how does the JSON contenr get a Go type in the first place?  I'm fine waiting to see the implementation of that's easier than explaining here.

**Comment by cyphar** [comment]
[Already implemented](https://github.com/cyphar/umoci/blob/master/image/cas/blob.go). Just wait for me to actually write the code (I already know how to do it in my head, and there's no real point in describing it in text when I can just write the damn thing).

**Comment by cyphar** [comment]
Implemented in e9a73d25f7f93d34870fc72e56f264b49de4aa69 and c71e790993b582f90063a83f44afb99d239a9bef.
