### ISSUE TITLE
hooks support

### ISSUE THREAD

**Issue by f0** [cyphar/umoci#61]
Does umoci support hooks? 
https://github.com/opencontainers/runtime-spec/blob/master/config.md#hooks

**Comment by cyphar** [comment]
`umoci` doesn't run containers. It just deals with packing and unpacking of images. Yes, part of unpacking images is creating a `config.json` -- however if you want to add hooks or stuff like that you should modify the `config.json` yourself (the `config.json` we currently generate is quite basic and only really contains all of the information from the OCI image that it was converted from).

**Comment by f0** [comment]
ok  understood -- is it just not on the priority list , or  you are against to support this in umoci?

**Comment by cyphar** [comment]
@f0 It's that I'm not really sure what there is to support when it comes to hooks. Do you want a flag to `umoci unpack` that allows you to set some hooks to the generated `config.json`? Why not just use [another tool to modify the `config.json` `umoci` generates](https://github.com/opencontainers/runtime-tools).

I don't _really_ want to re-invent `oci-runtime-tool generate` -- the purpose of the `config.json` extraction is to give you enough of a configuration that you can then go and modify with `oci-runtime-tool` or by yourself.

**Comment by f0** [comment]
@cyphar  using `oci-runtime-tool generate`  makes sense.  Thx
